from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    NONE = "NONE"


@dataclass(frozen=True, slots=True)
class Signal:
    """
    Trading signal generated by a strategy.
    """

    timestamp: datetime

    signal: SignalType

    price: float

    strategy: str

    reason: str