application:

  name: AstraQuant

  version: 1.0.0-alpha

market:

  symbol: NIFTY

  timeframe: 5m

strategy:

  active: DIDRS

didrs:

  itm_distance: 500

  discount_threshold: 20

  target: 30

  stoploss: 20